# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180321_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 18, 47, 20, 511470, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 18, 47, 20, 510969, tzinfo=utc)),
        ),
    ]
